version: '3.3'

services:
  web:
    build: backend
    container_name: backend-sprintmanager
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - backend/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: pgdb-sprintmanager
    volumes:
      - pgdb:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sprintmanager
      - POSTGRES_PASSWORD=sprintmanager
      - POSTGRES_DB=sprintmanager
    ports:
      - 5440:5432

volumes:
  pgdb: 