# Generated by Django 4.1.4 on 2023-01-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number_level', models.IntegerField(default=1)),
                ('days_min', models.IntegerField(default=3)),
                ('days_max', models.IntegerField(default=5)),
                ('devs_min', models.IntegerField(default=1)),
                ('devs_max', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Level',
                'ordering': ['number_level'],
            },
        ),
    ]
