# Generated by Django 4.1.4 on 2023-01-12 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('sprint', '0001_initial'),
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=200)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('forecast_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('TD', 'Aguardando'),
                            ('DG', 'Em produção'),
                            ('RW', 'Em Revisão'),
                            ('DN', 'Concluído'),
                        ],
                        default='TD',
                        max_length=2,
                    ),
                ),
                (
                    'categories',
                    models.ManyToManyField(
                        related_name='issue_categories', to='category.category'
                    ),
                ),
                (
                    'dependencies',
                    models.ManyToManyField(blank=True, to='issue.issue'),
                ),
                (
                    'level',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='level.level',
                    ),
                ),
                (
                    'sprint',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='sprint.sprint',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['begin_date', 'description'],
            },
        ),
    ]
