# Generated by Django 4.1.4 on 2023-01-12 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=200)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('forecast_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['begin_date', 'description'],
            },
        ),
    ]
